### ISSUE TITLE
raises "Hook with name 'enable_rescuing' already defined!" in ruby 2.5.x 

### ISSUE THREAD

**Issue by artm** [ConradIrwin/pry-rescue#109]
when trying to use pry-rescue with ruby 2.5.0 or 2.5.1 I get 

```
ArgumentError: Hook with name 'enable_rescuing' already defined!
  [...]/gems/pry-0.11.3/lib/pry/hooks.rb:74:in `add_hook'
  [...]/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:28:in `<top (required)>'
  [...]/gems/2.5.0/gems/pry-rescue-1.4.5/bin/rescue:51:in `require'
  [...]/gems/2.5.0/gems/pry-rescue-1.4.5/bin/rescue:51:in `<top (required)>'
  [...]/gems/2.5.0/bin/rescue:23:in `load'
  [...]/gems/2.5.0/bin/rescue:23:in `<top (required)>'
```
See [gist](https://gist.github.com/artm/dae2e2d2461d08cef6ad42eb09e28151) for more details.

**Comment by joallard** [comment]
Merged, let me know if anything
