### ISSUE TITLE
Pry-Rescue stops on enter_exception_context instead of the actual error

### ISSUE THREAD

**Issue by Pifoupif** [ConradIrwin/pry-rescue#124]
We have upgraded our stack recently and are now on rails 7.0.0 and ruby 3.1.1.

Since then when I run :
`PRY_RESCUE_RAILS=1 bundle exec rails test test/` (or every other ways of launching my test with pry-rescue) the context is stopped in the `enter_exception_context` rather than on the error itself:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/23505154/187615613-d5feff1e-c14b-41d8-8f0d-d6254da0e127.png">

Any idea how to fix this ?

**Comment by yann120** [comment]
I confirm that we are experiencing exactly the same issue on our side since few weeks...
I think the breaking change is since our gem upgrade : 
* pry from 0.13.1 to 0.14.1
* pry-byebug from 3.9.0 to 3.10.0

**Comment by StefanoMartin** [comment]
I want to confirm that the error is still present and it occurs with pry-byebug 3.10.1.

Working example:

```ruby
require 'pry-rescue'

def test
  raise "foo"
rescue => e
  raise "bar"
end

Pry.rescue do
  test
end
```

Work as expected:

```bash
Frame number: 0/6
Frame type: rescue

From: /home/user/testrescue.rb:6 Object#test:

    3: def test
    4:   raise "foo"
    5: rescue => e
 => 6:   raise "bar"
    7: end

RuntimeError: bar
from testrescue.rb:6:in `rescue in test'
Caused by RuntimeError: foo
from testrescue.rb:4:in `test'
```

Bad example:

```ruby
require 'pry-rescue'
require "pry-byebug"

def test
  raise "foo"
rescue => e
  raise "bar"
end

Pry.rescue do
  test
end
```

It does not work as expected:

```bash
Frame number: 0/23

From: /usr/share/rvm/gems/ruby-3.2.2/gems/pry-rescue-1.5.2/lib/pry-rescue.rb:65 PryRescue.enter_exception_context:

    46: def enter_exception_context(exception)
    47:   @any_exception_captured = true
    48:   @exception_context_depth ||= 0
    49:   @exception_context_depth += 1
    50: 
    51:   exception = exception.instance_variable_get(:@rescue_cause) if phantom_load_raise?(exception)
    52:   bindings = exception.instance_variable_get(:@rescue_bindings)
    53: 
    54:   bindings = without_bindings_below_raise(bindings)
    55:   bindings = without_duplicates(bindings)
    56: 
    57:   with_program_name "#$PROGRAM_NAME [in pry-rescue @ #{Dir.pwd}]" do
    58:     if defined?(PryStackExplorer)
    59:       pry :call_stack => bindings,
    60:           :hooks => pry_hooks(exception),
    61:           :initial_frame => initial_frame(bindings)
    62:     else
    63:       Pry.start bindings.first, :hooks => pry_hooks(exception)
    64:     end
 => 65:   end
    66: ensure
    67:   @exception_context_depth -= 1
    68: end

```

This is quite an issue because both the libraries (pry-rescue and pry-byebug) are important, and downgrade is not possible since the old version of bye-prybug does not support Ruby 3.2.

**Comment by afn** [comment]
See https://github.com/deivid-rodriguez/pry-byebug/pull/422 --- this disables byebug when pry is invoked by pry-rescue.

Gemfile:
```ruby
gem 'pry-byebug', github: 'cygnuseducation/pry-byebug'
```

**Comment by idrozd** [comment]
@afn jesus, thanks! Finally
