### ISSUE TITLE
When peeking via SIGQUIT, every 'require' causes an error

### ISSUE THREAD

**Issue by zach** [ConradIrwin/pry-rescue#52]
I have had poor luck with getting peek to work via Ctrl-\ since every `require` statement seems to cause an error, worst of all being those in Pry `:before_session` hooks and those from CodeRay autoloads. As a result, I never get to see the code I'm trying to peek at, nor can I explore the stack or the other stuff. I really like this functionality and would love to make this work, but if `require` doesn't work I don't understand how it ever did.

Here are some example sessions:

```
^\Preparing to peek via pry!
require 'pry-debugger' # Failed, saying: can't be called from trap context

Frame number: 0/44
Frame type: method
before_session hook failed: ThreadError: can't be called from trap context
```

(hangs)

```
^\Preparing to peek via pry!
require 'pry-debugger' # Failed, saying: can't be called from trap context
require 'pry-doc' # Failed, saying: can't be called from trap context
require 'pry-git' # Failed, saying: can't be called from trap context
require 'pry-rails' # Failed, saying: can't be called from trap context
require 'pry-remote' # Failed, saying: can't be called from trap context

Frame number: 0/2
Frame type: block
before_session hook failed: ThreadError: can't be called from trap context
/Users/zach/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/coderay-1.1.0/lib/coderay.rb:169:in `scan'
(see _pry_.hooks.errors to debug)
before_session hook failed: ThreadError: can't be called from trap context
/Users/zach/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/interception-0.3/lib/interception.rb:64:in `synchronize'
(see _pry_.hooks.errors to debug)
[1] (pry) main: 0> up
ThreadError: can't be called from trap context
from /Users/zach/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/coderay-1.1.0/lib/coderay.rb:169:in `scan'
[1] (pry) main: 0>
```

This is in Ruby 2.0 on OS X 10.9. Maybe there's something I don't have configured properly, but even a simple script that I break into with Ctrl-\ has this problem. I made a repo with this example (run main.rb and use Ctrl-\ or just run the test script and peek after it prints the first line of numbers):

https://github.com/zach/pry-rescue-peek-test

Why does this seem to work in other circumstances and yet I can't seem to make this work? Is this a Bundler-related issue?

**Comment by stdedos** [comment]
Similar backtrace:

```ruby
[5] pry(Timeout)> yield(0)
^\Preparing to peek via pry!
ThreadError: can't be called from trap context
from /data/ruby/lib/ruby/2.4.0/monitor.rb:187:in `lock'
[6] pry(Timeout)> bt
=> nil
[7] pry(Timeout)> backtrace
--> #0  #<Class:Timeout>.timeout(sec#Float, klass#NilClass, message#NilClass) at /spool/ruby/lib/ruby/2.4.0/timeout.rb:77

```
