### ISSUE TITLE
bundle exec rescue rspec does not automatically open pry when test fails.

### ISSUE THREAD

**Issue by magicalbanana** [ConradIrwin/pry-rescue#81]
I know this was already mentioned but why is not working anymore? Anyone know of a fix?

**Comment by kyrylo** [comment]
Hi, @magicalbanana! What do you mean by "doesn't work"? Do you see any errors?

**Comment by magicalbanana** [comment]
@kyrylo like pry isn't called automatically when I execute the command and there's an error or exception that was called.

Before, I remember it get's called so trying to figure out why it does not do that anymore.

Here's my pry gems:

```
group :development do
  # Model Annotation
  gem 'annotate', '~> 2.6.5'

  gem 'web-console', '~> 2.0'
  gem 'spring', '~> 1.3.2'

  # Pry
  gem 'pry-rails', '0.3.3'
  gem 'pry-byebug', '~> 2.0.0'
  gem 'pry-rescue', '~> 1.4.1'
  gem 'pry-stack_explorer', '~> 0.4.9.2'
end
```

**Comment by magicalbanana** [comment]
Anyone out there? :cry: 

Basically my issue is that it does not open pry anymore when there's an exception.

Additionally I use:

rails 4.2.0
rspec 3.2.0

**Comment by magicalbanana** [comment]
```
| ~/Git/level_up_exercises/cyoa/svajone_page @ CLM-KGAN (kgan)
| => berr ./spec/services/weather_forecast/process_spec.rb:39 -b
Run options: include {:focus=>true, :locations=>{"./spec/services/weather_forecast/process_spec.rb"=>[39]}}

Randomized with seed 24834

WeatherForecast::Process
  #call
    when request && point == true
      prints something out (FAILED - 1)

Failures:

  1) WeatherForecast::Process#call when request && point == true prints something out
     Failure/Error: process.call
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./app/services/weather_forecast/process.rb:39:in `block in call'
     # ./app/services/weather_forecast/process.rb:34:in `each'
     # ./app/services/weather_forecast/process.rb:34:in `call'
     # ./spec/services/weather_forecast/process_spec.rb:33:in `block (4 levels) in <top (required)>'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:177:in `instance_exec'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:177:in `block in run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:385:in `block in with_around_and_singleton_context_hooks'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:343:in `block in with_around_example_hooks'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:474:in `block in run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:614:in `block in run_around_example_hooks_for'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-rails-3.2.1/lib/rspec/rails/adapters.rb:113:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:387:in `execute_with'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:616:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # ./spec/support/vrc.rb:12:in `block (3 levels) in <top (required)>'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/vcr-2.9.3/lib/vcr.rb:182:in `use_cassette'
     # ./spec/support/vrc.rb:12:in `block (2 levels) in <top (required)>'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:387:in `execute_with'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:616:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/rspec.rb:14:in `block in run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/interception-0.5/lib/interception.rb:71:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/interception-0.5/lib/interception.rb:71:in `listen'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/core_ext.rb:74:in `enable_rescuing!'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/core_ext.rb:94:in `with_rescuing'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/core_ext.rb:15:in `block (2 levels) in rescue'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/core_ext.rb:13:in `catch'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/core_ext.rb:13:in `block in rescue'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/core_ext.rb:12:in `loop'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/core_ext.rb:12:in `rescue'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/rspec.rb:9:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pry-rescue-1.4.1/lib/pry-rescue/rspec.rb:56:in `block (2 levels) in <top (required)>'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:387:in `execute_with'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:616:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:247:in `call'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:617:in `run_around_example_hooks_for'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/hooks.rb:474:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:343:in `with_around_example_hooks'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:385:in `with_around_and_singleton_context_hooks'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example.rb:174:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:548:in `block in run_examples'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:544:in `map'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:544:in `run_examples'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:512:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:513:in `block in run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:513:in `map'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:513:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:513:in `block in run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:513:in `map'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/example_group.rb:513:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:110:in `block (3 levels) in run_specs'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:110:in `map'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:110:in `block (2 levels) in run_specs'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1526:in `with_suite_hooks'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:109:in `block in run_specs'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/reporter.rb:62:in `report'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:108:in `run_specs'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:86:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:70:in `run'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:38:in `invoke'
     # /Users/kgan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/exe/rspec:4:in `<top (required)>'
     # /Users/kgan/.rbenv/versions/2.2.1/bin/rspec:23:in `load'
     # /Users/kgan/.rbenv/versions/2.2.1/bin/rspec:23:in `<main>'

Top 1 slowest examples (0.61355 seconds, 91.7% of total time):
  WeatherForecast::Process#call when request && point == true prints something out
    0.61355 seconds ./spec/services/weather_forecast/process_spec.rb:32

Finished in 0.66903 seconds (files took 2.55 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/services/weather_forecast/process_spec.rb:32 # WeatherForecast::Process#call when request && point == true prints something out
```

Hope someone sees this.

**Comment by ConradIrwin** [comment]
@magicalbanana Could you make a really simple example repo that reproduces this problem?

**Comment by magicalbanana** [comment]
@ConradIrwin sure, but maybe later. But I managed to fix it by changing my RSpec version to 3.1.0 (I looked at my old repos because those worked).

Perhaps it's time to update this sir.

**Comment by paulodiovani** [comment]
I have the same problem. The test just fails, not breaking on `pry`.
My gems:

```
group :development, :test do
  gem 'dotenv-rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'pry-rescue', '~> 1.4.1'
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'launchy'
  gem 'awesome_print'
  gem 'did_you_mean'
end
```

**Comment by gerrywastaken** [comment]
If 1.4.2 fixes this, will it be uploaded to rubygems?

**Comment by ConradIrwin** [comment]
Pushed. Sorry!

**Comment by gerrywastaken** [comment]
@ConradIrwin No worries, thanks for the fast response. :)
