### ISSUE TITLE
rspec isn't part of the bundle when using rspec-rails

### ISSUE THREAD

**Issue by tombruijn** [ConradIrwin/pry-rescue#87]
`rspec` isn't always part of the bundle while you still want to use it. In `rspec-rails` the actual `rspec` gem isn't a dependecy, instead it links all the `rspec-*` gems in its own gemspec.

Issue #81 / commit 5c1eb5fd7ad83e7c109ca39f0a3137c207d458c1 introduces the problem of needing the `rspec` gem all the time.

```
bundle exec rescue rspec
/Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- rspec (LoadError)
	from /Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
	from /Users/tom/.gem/ruby/2.2.2/gems/pry-rescue-1.4.2/lib/pry-rescue/rspec.rb:2:in `<top (required)>'
	from /Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
	from /Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/tom/.gem/ruby/2.2.2/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1181:in `block in requires='
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1181:in `each'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1181:in `requires='
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration_options.rb:110:in `block in process_options_into'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration_options.rb:109:in `each'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration_options.rb:109:in `process_options_into'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
	from /Users/tom/.gem/ruby/2.2.2/bin/rspec:23:in `load'
	from /Users/tom/.gem/ruby/2.2.2/bin/rspec:23:in `<main>'
```

The workaround is: adding the `rspec` gem the Gemfile along with `rspec-rails`. Then it can actually load the ["RSpec meta-gem that depends on the other components"](https://github.com/rspec/rspec).

So I think this require call might need to be wrapped in a begin/rescue block instead?

**Comment by eliotsykes** [comment]
Experienced a similar error that was fixed by adding `gem 'rspec'` alongside the existing `gem 'rspec-rails'`. Thanks @tombruijn
